apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <INSERT_KEY_HERE>
    server: https://0.0.0.0:45617
  name: k3d-my-cluster
contexts:
- context:
    cluster: k3d-my-cluster
    user: admin@k3d-my-cluster
  name: k3d-my-cluster
current-context: k3d-my-cluster
kind: Config
preferences: {}
users:
- name: admin@k3d-my-cluster
  user:
    client-certificate-data: <INSERT_KEY_HERE>
    client-key-data: <INSERT_KEY_HERE>
